spring:
  application:
    name: upms-web
# 特定Profile属性从跟标准application.properties相同的路径加载，并且特定profile文件会覆盖默认的配置。
  profiles:
    active: ${UPMS_SPRING_PROFILES_ACTIVE:dev}
    include: mybatis,log
# HTTP encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# AOP
  aop:
    auto: true
    proxy-target-class: true

server:
  port: ${UPMS_SERVER_PORT:8080}
